# Generated by Django 5.0.4 on 2024-04-28 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('path_saved_order', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('as_active', models.BooleanField(default=True)),
                ('path_saved_reports', models.CharField(max_length=255)),
                ('id_pg_contract', models.IntegerField(default=0)),
                ('id_groups_goods', models.IntegerField(default=0)),
                ('id_groups_vod', models.IntegerField(default=0)),
                ('id_groups_vod_tls', models.IntegerField(default=0)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base_app.filial')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ('position',),
            },
        ),
    ]
