# Generated by Django 5.0.4 on 2024-04-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='id_pg_contract',
        ),
    ]
