# Generated by Django 5.0.4 on 2024-04-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_remove_contracts_id_pg_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='connect_pg_str',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='prog_id',
            field=models.IntegerField(default=0),
        ),
    ]
