# Generated by Django 5.0.4 on 2024-04-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_rename_dsn_filial_url_pg_filial_url_wms'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='login_wms',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='password_wms',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
