# Generated by Django 5.0.4 on 2024-04-30 17:00

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_filial_login_wms_filial_password_wms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('position', models.IntegerField(default=0)),
                ('as_active', models.BooleanField(default=True)),
                ('contract', models.ManyToManyField(related_name='operations', to='base_app.contracts')),
            ],
        ),
    ]
