# Generated by Django 5.0.4 on 2024-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_operations_btn_label_operations_load_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='load_stock',
            field=models.BooleanField(default=True),
        ),
    ]
