# Generated by Django 5.0.4 on 2024-04-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_operations_load_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='load_file',
            new_name='load_orders',
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='load_stock',
            new_name='load_stock_pg',
        ),
        migrations.AddField(
            model_name='operations',
            name='load_stock_wms',
            field=models.BooleanField(default=True),
        ),
    ]
