# Generated by Django 5.0.4 on 2024-04-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_rename_load_file_operations_load_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
    ]
