# Generated by Django 5.0.4 on 2024-05-01 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_rename_load_orders_operations_load_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operations',
            options={'ordering': ('position',), 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AddField(
            model_name='contracts',
            name='operation',
            field=models.ManyToManyField(to='base_app.operations', verbose_name='Операции'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='as_active',
            field=models.BooleanField(default=True, verbose_name='Признак активности'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base_app.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='id_groups_goods',
            field=models.IntegerField(default=0, verbose_name='Код папки товаров'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='id_groups_vod',
            field=models.IntegerField(default=0, verbose_name='Код папки водителей, для ОК'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='id_groups_vod_tls',
            field=models.IntegerField(default=0, verbose_name='Код папки водителей ТЛС, для ОК'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='path_saved_order',
            field=models.CharField(max_length=255, verbose_name='Папка сохранения заявок XML'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='path_saved_reports',
            field=models.CharField(max_length=255, verbose_name='Папка сохранения отчетов'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция в меню'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='as_active',
            field=models.BooleanField(default=True, verbose_name='Признак активности'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='login_wms',
            field=models.CharField(max_length=255, verbose_name='Логин WMS'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='password_wms',
            field=models.CharField(max_length=255, verbose_name='Пароль WMS'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция в меню'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='prog_id',
            field=models.IntegerField(default=0, verbose_name='Код программы Логистика'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='url_pg',
            field=models.CharField(max_length=255, verbose_name='Строка подключения к PG'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='url_wms',
            field=models.CharField(max_length=255, verbose_name='Строка подключения к WMS'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='as_active',
            field=models.BooleanField(default=True, verbose_name='Признак активности'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='base_app.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='as_active',
            field=models.BooleanField(default=True, verbose_name='Признак активности'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='btn_label',
            field=models.CharField(max_length=155, verbose_name='Надпись на кнопке'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='contract',
            field=models.ManyToManyField(related_name='operations', to='base_app.contracts', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='load_file',
            field=models.BooleanField(default=True, verbose_name='Форма загрузки заявки'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='load_stock',
            field=models.BooleanField(default=True, verbose_name='Форма загрузки остатков'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция в меню'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='search_goods',
            field=models.BooleanField(default=True, verbose_name='Форма проверки товара в сетевом'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
