# Generated by Django 5.0.4 on 2024-05-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_remove_contracts_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('path_saved_reports', models.CharField(max_length=255, verbose_name='Папка сохранения отчетов')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base_app.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ('position',),
            },
        ),
    ]
