# Generated by Django 5.0.4 on 2024-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='path_skud',
            field=models.CharField(default=1, max_length=255, verbose_name='Путь к папке скуд для филиала'),
            preserve_default=False,
        ),
    ]
