# Generated by Django 5.0.4 on 2024-11-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_filial_path_skud'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='id_client',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Код клиента'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='id_postav',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Код поставщика'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='id_sklad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Код склада'),
        ),
    ]
