# Generated by Django 5.0.4 on 2025-03-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_contracts_id_client_contracts_id_postav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='id_agent',
            field=models.IntegerField(default=0, verbose_name='Код агента'),
        ),
    ]
