# Generated by Django 5.0.4 on 2025-03-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_contracts_id_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='id_agent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Код агента'),
        ),
    ]
