# Generated by Django 5.0.4 on 2025-03-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_alter_contracts_id_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='delivery_type',
            field=models.IntegerField(default=2, verbose_name='Тип доставки'),
        ),
    ]
