# Generated by Django 5.0.4 on 2025-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("slug", models.SlugField(max_length=255, verbose_name="URL")),
                (
                    "path_saved_reports",
                    models.CharField(
                        max_length=255, verbose_name="Папка сохранения отчетов"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, verbose_name="Позиция в меню"),
                ),
                (
                    "as_active",
                    models.BooleanField(
                        default=True, verbose_name="Признак активности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
                "ordering": ("position",),
            },
        ),
    ]
