# Generated by Django 5.0.4 on 2024-11-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0020_contracts_id_client_contracts_id_postav_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=155, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=155, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=155, verbose_name='Отчество')),
                ('full_name', models.CharField(max_length=155, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('last_name', 'first_name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='DataSkud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155, verbose_name='Сотрудник')),
                ('getting_started', models.DateField()),
                ('end_of_work', models.DateField()),
                ('type_direction', models.CharField(max_length=155, verbose_name='Направление')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_skud_filial', to='base_app.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Данные Скуд',
                'verbose_name_plural': 'Данные Скуд',
                'ordering': ('filial', 'full_name'),
            },
        ),
    ]
